### ISSUE TITLE
Relicense under OSI-approved license

### ISSUE THREAD

**Issue by bd808** [bd808/wikimedia-cloud-vps-hostgroup-generator#1]
I would like to move this project from the initial CC0 license chosen by @yuvipanda for the origin repo at https://github.com/yuvipanda/personal-wiki to a license that is [approved by the Open Source Initiative](https://opensource.org/licenses). Doing so will make using this software in Wikimedia's Cloud Services platform easier.

I would propose the [MIT license](https://opensource.org/licenses/MIT) as the most widely used permissive license (in my opinion) in the OSI-approved list. Currently the only documented contributors to these works are myself and @yuvipanda, so with his approval the re-licensing can be performed.

**Comment by bd808** [comment]
Technically I believe that a CC0 licensed product can be arbitrarily re-licensed in a fork based on my understanding of the [CC0 release of rights](https://wiki.creativecommons.org/wiki/CC0_FAQ#Can_I_control_how_my_work_is_being_used_once_I_publish_it_using_CC0.3F), but I'd still like @yuvipanda's approval because its the nice thing to do.

**Comment by yuvipanda** [comment]
Absolutely, feel free! I prefer Apache2 myself but MIT is great too.

**Comment by bd808** [comment]
Apache2 sounds good to me too. I suggested MIT just because it was the "most permissive".
